apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-stable
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-web
  template:
    metadata:
      labels:
        app: stable-web
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Image officielle, multi-arch
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stable-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: stable-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30700  # Port tout neuf pour Ã©viter les conflits
